import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/nav/Navbar";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className="pretendard flex min-h-screen flex-col bg-gray-100 antialiased"
        cz-shortcut-listen="true"
      >
        <header role="banner" aria-label="주요 네비게이션">
          <Navbar />
        </header>
        <section
          className="max-w-screen mx-[30px] flex-grow bg-teal"
          aria-labelledby="main-content"
        >
          {children}
        </section>
        <footer role="contentinfo" aria-label="사이트 하단 정보">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
