import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className="pretendard flex min-h-screen flex-col bg-gray-100 antialiased"
        cz-shortcut-listen="true"
      >
        <header>
          <Navbar />
        </header>
        <section className="max-w-screen mx-[30px] flex-grow bg-teal">
          {children}
        </section>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
