import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/nav/Navbar";
import Footer from "../components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className="flex min-h-screen flex-col bg-gray-100 font-Pretendard antialiased"
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
